### ISSUE TITLE
Empty page 500 error

### ISSUE THREAD

**Issue by tukker01** [comwrap/Comwrap_ElasticsuiteBlog#4]
When installing Comwrap_ElasticsuiteBlog the search is not working anymore and no results

Developer modus on give this result

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel aboutus' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 919

Element 'block', attribute 'as': 'cpanel aboutus' is not a valid value of the atomic type 'elementAliasType'.
Line: 919

Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel above main' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 925

Element 'block', attribute 'as': 'cpanel above main' is not a valid value of the atomic type 'elementAliasType'.
Line: 925

Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel below main' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 928

Element 'block', attribute 'as': 'cpanel below main' is not a valid value of the atomic type 'elementAliasType'.
Line: 928

Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel ajax loader' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 931

Element 'block', attribute 'as': 'cpanel ajax loader' is not a valid value of the atomic type 'elementAliasType'.
Line: 931

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel aboutus' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 919

Element 'block', attribute 'as': 'cpanel aboutus' is not a valid value of the atomic type 'elementAliasType'.
Line: 919

Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel above main' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 925

Element 'block', attribute 'as': 'cpanel above main' is not a valid value of the atomic type 'elementAliasType'.
Line: 925

Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel below main' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 928

Element 'block', attribute 'as': 'cpanel below main' is not a valid value of the atomic type 'elementAliasType'.
Line: 928

Element 'block', attribute 'as': [facet 'pattern'] The value 'cpanel ajax loader' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_\.]*'.
Line: 931

Element 'block', attribute 'as': 'cpanel ajax loader' is not a valid value of the atomic type 'elementAliasType'.
Line: 931

#0 /var/www/html/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/html/v...', '%message%\nLine:...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#4 /var/www/html/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/html/vendor/magento/framework/View/Model/Layout/Update/Validator.php(141): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /var/www/html/vendor/magento/framework/View/Model/Layout/Merge.php(464): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /var/www/html/vendor/magento/framework/View/Model/Layout/Merge.php(445): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<body>\n   <refe...')
#8 /var/www/html/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(193): Magento\Framework\View\Model\Layout\Merge->load(Array)
#9 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge\Interceptor->load()
#10 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#11 /var/www/html/vendor/magento/framework/View/Page/Config.php(208): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/html/vendor/magento/framework/View/Page/Config.php(218): Magento\Framework\View\Page\Config->build()
#13 /var/www/html/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#14 /var/www/html/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#15 /var/www/html/vendor/magento/module-catalog-search/Controller/Result/Index.php(147): Magento\Framework\App\View->loadLayout()
#16 /var/www/html/vendor/magento/module-catalog-search/Controller/Result/Index.php(93): Magento\CatalogSearch\Controller\Result\Index->getNotCacheableResult(Object(Magento\CatalogSearch\Helper\Data), Object(Magento\Search\Model\Query\Interceptor))
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Controller\Result\Index->execute()
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('execute', Array)
#19 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php(98): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Smile\ElasticsuiteCatalog\Plugin\CatalogSearch\ResultPlugin->aroundExecute(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure))
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/html/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(26): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('execute', Array, NULL)
#23 /var/www/html/vendor/magento/framework/App/Action/Action.php(107): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute()
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(39): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/www/html/vendor/magento/framework/App/FrontController.php(55): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#31 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#37 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#39 /var/www/html/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#40 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#41 {main}

**Comment by nuzil** [comment]
Hi @tukker01, thanks a lot for your feedback.
Can you please specify your version of Smile/Elasticsuite extension you are using?

**Comment by tukker01** [comment]
Sorry for the late response we are using 2.6.1
